### ISSUE TITLE
Readme review

### ISSUE THREAD

**Issue by augustogoncalves** [Autodesk-Forge/forge-bim360-assets.viewer#1]
- Adjust badges: Viewer v7, add Assets,
- Description: links are pointing to developer.autodesk.com, adjust to forge.autodesk.com, Viewer link points to v6, and has a "under construction" line...
- Please have at lest 1 `thumbnail.png` (exact name, so it appears on the list, `thumbnail-1.png` will not work)
- Suggestion: write on the thumbnail, over the panel, a text indicating the extension name (mentioned on the text), makes easier to identify what is what
- Some images have links to videos, please add a text with link
- Live link not working: https://bim360assets.herokuapp.com
- At the end of [Work with your models](https://github.com/yiskang/forge-bim360-assets#work-with-your-models) section you point to other samples, please move that to "Further reading"
- [Running locally](https://github.com/yiskang/forge-bim360-assets#running-locally) sections seems to be missing images
- "Further reading" section contains links to bim360-private and some TDB
-

**Comment by yiskang** [comment]
Thank you for your kind feedback. I followed your suggestions to update most of the README content but left the TBD items since we're still reviewing the tutorial and waiting for the real links to them. I will update them after everything is done by the engineering team.

**Comment by yiskang** [comment]
Updated with this PR https://github.com/Autodesk-Forge/forge-bim360-assets.viewer/pull/2
